###################### MODULES CONFIGURATION (REQUIRED) ########################
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

############################# FILEBEAT INPUTS ##################################
filebeat.inputs:
  - type: filestream
    id: system-logs
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/auth.log
      - /var/log/kern.log
      - /var/log/dpkg.log

############################## FILEBEAT MODULES ################################
filebeat.modules:
  - module: system
    syslog:
      enabled: true
      var.paths: ["/var/log/syslog"]
    auth:
      enabled: true
      var.paths: ["/var/log/auth.log"]

################################ PROCESSORS ####################################
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

########################### OUTPUT TO ELASTICSEARCH ############################
output.elasticsearch:
  hosts: ["http://localhost:9200"]
  protocol: "http"

################################# FILEBEAT LOGGING #############################
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644